module.exports = {
  surveyUpdated: 'Successfully updated Survey Details',
  surveyDeletedNotAffected: 'Either Survey is already deleted or SurveyID does not exists.',
  surveyCreated: 'Successfully created Survey',
  surveyFetched: 'Successfully Fetched Survey Details',
  surveyDeleted: 'Successfully Deleted Survey',
  questionCreated: 'Successfully created Question',
  questionFetched: 'Successfully Fetched Question Details',
  questionDeleted: 'Successfully Deleted Question',
  surveyPublished: 'Successfully Published Survey',
  dataFetched: 'Successfully Fetched Details',
  surveyResCreated: 'Successfully created Survey Response',
  surveyResFetched: 'Successfully Fetched Survey Response',
  surveyResUpdated: 'Successfully updated Survey Response',
  surveyUpdated: 'Successfully updated Survey',
  surveyResDeleted: 'Successfully Deleted Survey Response',
  surveyResDeletedNotAffected:
    'Either Survey Response is already deleted or SurveyID does not exists.',
  tokenIssue: 'Improper token',
  tokenMissing: 'Please send token',
  success: 'Success',
  dbError: 'Unable to process your request, please try again',
  sessionExpire: 'Session expires. Please login again',
  invalidDetails: 'Invalid details',
  tryCatch: 'Something went wrong. Please contact admin.',
  dataIssue: 'Please send proper information',
  oAuthdataIssue: 'Unable to parse data from JWT (Property/Usertype/Unit)',
  registration: 'Registration done successfully',
  invalidEmail: 'Please insert email address in correct format',
  invalidLoginDetails: 'Invalid login details',
  accountDisable: 'Your account is blocked by admin. Please contact admin.',
  emailVerify: 'Please complete email verification process',
  emailVerificationSuccess: 'Email address successfully verified. Please login to continue',
  emailLinkExpired: 'Link has expired.',
  registrationEmailSubject: 'Welcome to CommonAPI',
  passwordChanged: 'Password changed successfully',
  forgotPasswordSubject: 'Common API, Forgot password link',
  resetLink:
    'Reset link sent successfully. You will receive a link shortly if a user is registered.',
  passwordReset: 'Password has been successfully reset. Please login',
  profileUpdate: 'Profile updated successfully',
  allFieldReq: 'Please fill all required fields',
  noData: 'No information available',
  csvDataAdded: 'CSV data added successfully'
};
